logging:
  level:
    sa:
      springframework: debug
    org:
      springframework:
        security: trace

server:
  port: 8084


spring:
  profiles:
    active:
      - postgre
  security:
    user:
      name: admin
      password: 1905
