spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: create-drop
  show-sql: true
  format-sql: true


spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5400/postgres
  username: admin
  password: 1905
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind:
              - TRACE
spring:
  flyway:
    enabled: true